language: python
dist: trusty
cache: pip
notifications:
  email: false
python:
  - 3.6
env:
  - "DASHBOARD_CONFIG_INI=tests/sso-dashboard.ini AWS_DEFAULT_REGION=us-west-2"
before_install:
  - pip install flake8
  - flake8 dashboard
  - flake8 tests
install:
  - pip install -r requirements.txt
  - npm install -g eslint stylelint
script:
  - python setup.py pytest
  - eslint 'dashboard/static/js/*.js'
  - stylelint 'dashboard/static/css/*.scss'
