language: python
dist: trusty
cache: pip
notifications:
  email: false
python:
  - 3.6
env:
  - DASHBOARD_CONFIG_INI='tests/sso-dashboard.ini'
before_install:
  - pip install flake8
  - pip install moto
  - flake8 dashboard
  - flake8 tests
install:
  - pip install -r requirements.txt
  - npm install -g eslint stylelint
script:
  - pytest
  - eslint 'dashboard/static/js/*.js'
  - stylelint 'dashboard/static/css/*.scss'
