AWSTemplateFormatVersion: "2010-09-09"
Description: "Mozilla Single Sign On Dashboard Alert Feedback Queues"
Resources:
  AlertFeedbackSQS:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "SSODashboardAlertFeedback"
  AlertFeedbackSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint:
            Fn::GetAtt:
              - "AlertFeedbackSQS"
              - "Arn"
          Protocol: "sqs"
      TopicName: "SSODashboardAlertFeedback"
