AWSTemplateFormatVersion: "2010-09-09"
Description: "Mozilla Single Sign On Dashboard Roles"
Resources:
  SSODashboardRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
                - "ssm.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
      RoleName: sso-dashboard-delivery-server
  SSOInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    DependsOn: SSODashboardRole
    Properties:
      InstanceProfileName: "sso-dashboard-instance-profile-v1"
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardCodePipelineAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:GetBucketAcl"
              - "s3:GetBucketCORS"
              - "s3:GetBucketLocation"
              - "s3:GetBucketLogging"
              - "s3:GetBucketNotification"
              - "s3:GetBucketPolicy"
              - "s3:GetBucketRequestPayment"
              - "s3:GetBucketTagging"
              - "s3:GetBucketVersioning"
              - "s3:GetBucketWebsite"
              - "s3:GetLifecycleConfiguration"
              - "s3:GetObject"
              - "s3:GetObjectAcl"
              - "s3:GetObjectTagging"
              - "s3:GetObjectTorrent"
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionAcl"
              - "s3:GetObjectVersionTagging"
              - "s3:GetObjectVersionTorrent"
              - "s3:GetReplicationConfiguration"
              - "s3:ListAllMyBuckets"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:ListBucketVersions"
              - "s3:ListMultipartUploadParts"
            Resource: "arn:aws:s3:::codepipeline*"
      PolicyName: sso-dashboard-read-codepipeline
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardS3Access:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:GetBucketAcl"
              - "s3:GetBucketCORS"
              - "s3:GetBucketLocation"
              - "s3:GetBucketLogging"
              - "s3:GetBucketNotification"
              - "s3:GetBucketPolicy"
              - "s3:GetBucketRequestPayment"
              - "s3:GetBucketTagging"
              - "s3:GetBucketVersioning"
              - "s3:GetBucketWebsite"
              - "s3:GetLifecycleConfiguration"
              - "s3:GetObject"
              - "s3:GetObjectAcl"
              - "s3:GetObjectTagging"
              - "s3:GetObjectTorrent"
              - "s3:GetObjectVersion"
              - "s3:GetObjectVersionAcl"
              - "s3:GetObjectVersionTagging"
              - "s3:GetObjectVersionTorrent"
              - "s3:GetReplicationConfiguration"
              - "s3:ListAllMyBuckets"
              - "s3:ListBucket"
              - "s3:ListBucketMultipartUploads"
              - "s3:ListBucketVersions"
              - "s3:ListMultipartUploadParts"
            Resource: "arn:aws:s3:::sso-dashboard.*"
      PolicyName: sso-dashboard-read-buckets
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardCloudWatchAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:DescribeLogGroups"
              - "logs:DescribeLogStreams"
              - "logs:PutLogEvents"
              - "logs:GetLogEvents"
              - "logs:FilterLogEvents"
            Resource: "*"
      PolicyName: sso-dashboard-cloudwatch-log
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardECRLogin:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource: "*"
      PolicyName: sso-dashboard-ecr-login
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardSQSSend:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "sqs:ChangeMessageVisibility"
              - "sqs:ChangeMessageVisibilityBatch"
              - "sqs:CreateQueue"
              - "sqs:GetQueueAttributes"
              - "sqs:GetQueueUrl"
              - "sqs:ListDeadLetterSourceQueues"
              - "sqs:ListQueues"
              - "sqs:PurgeQueue"
              - "sqs:ReceiveMessage"
              - "sqs:SendMessage"
              - "sqs:SendMessageBatch"
              - "sqs:SetQueueAttributes"
            Resource: "arn:aws:sqs:*:*:sso-dashboard-fluentd-sqs"
      PolicyName: sso-dashboard-sqs-send
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardSNSNotify:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "SNS:Publish"

            Resource: "arn:aws:sns:*:*:sso-dashboard-*"
      PolicyName: sso-dashboard-sns-send
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardCredstashRead:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
            Resource: "arn:aws:dynamodb:*:*:table/credential-store"
      PolicyName: sso-dashboard-credstash
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardAlertWrite:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
                - "dynamodb:DeleteItem"
                - "dynamodb:DescribeLimits"
                - "dynamodb:DescribeReservedCapacity"
                - "dynamodb:DescribeReservedCapacityOfferings"
                - "dynamodb:DescribeStream"
                - "dynamodb:DescribeTable"
                - "dynamodb:GetItem"
                - "dynamodb:GetRecords"
                - "dynamodb:GetShardIterator"
                - "dynamodb:ListTables"
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:Scan"
                - "dynamodb:UpdateItem"
            Resource: "arn:aws:dynamodb:*:*:table/sso-dashboard-alert"
      PolicyName: sso-dashboard-alert-write
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardConfigurationRead:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
                - "dynamodb:DeleteItem"
                - "dynamodb:DescribeLimits"
                - "dynamodb:DescribeReservedCapacity"
                - "dynamodb:DescribeReservedCapacityOfferings"
                - "dynamodb:DescribeStream"
                - "dynamodb:DescribeTable"
                - "dynamodb:GetItem"
                - "dynamodb:GetRecords"
                - "dynamodb:GetShardIterator"
                - "dynamodb:ListTables"
                - "dynamodb:PutItem"
                - "dynamodb:Query"
                - "dynamodb:Scan"
                - "dynamodb:UpdateItem"
                - "dynamodb:UpdateItem"
            Resource: "arn:aws:dynamodb:*:*:table/sso-dashboard-apps"
      PolicyName: sso-dashboard-configuration-read
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardTagAccess:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ec2:DescribeTags"
            Resource: "*"
      PolicyName: sso-dashboard-describe-tags
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardCodeDeploy:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "codedeploy:*"
            Resource: "arn:aws:codedeploy:*:*:application:sso-dashboard-*"
      PolicyName: sso-dashboard-code-deploy
      Roles:
        -
          Ref: SSODashboardRole
  SSODashboardParameterStore:
    Type: "AWS::IAM::Policy"
    DependsOn: SSODashboardRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:*:*:parameter/sso-dashboard-alerts-sns"
      PolicyName: sso-dashboard-parameter-store
      Roles:
        -
          Ref: SSODashboardRole
