AWSTemplateFormatVersion: "2010-09-09"
Description: "Mozilla Single Sign On Dashboard"
Mappings:
  dev:
      us-west-2:
        AMI: ami-069d1e7e
        branch: "git checkout master"
        CertificateARN: "arn:aws:acm:us-west-2:656532927350:certificate/39900f53-5c37-44b4-aa4b-9c48f1de9a9d"
  prod:
      us-west-2:
        AMI: ami-b99e1dc1
        branch: "git checkout production"
        CertificateARN: "arn:aws:acm:us-west-2:371522382791:certificate/fd8b3557-6b01-41fe-b7f4-ae726ec4ea56"
Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  EnvType:
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - dev
Conditions:
  UseProdCondition:
    !Equals [!Ref EnvType, prod]
  UseDevCondition:
    !Equals [!Ref EnvType, dev]
Resources:
  SSODashboardInternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  SSODashboardVPC:
    Type: "AWS::EC2::VPC"
    DependsOn: SSODashboardInternetGateway
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: True
      EnableDnsHostnames: True
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn: SSODashboardVPC
    Properties:
      VpcId:
        Ref: SSODashboardVPC
      InternetGatewayId:
        Ref: SSODashboardInternetGateway
  SSODashboardRouteTable:
    Type: "AWS::EC2::RouteTable"
    DependsOn: [ SSODashboardVPC, SSODashboardInternetGateway, AttachGateway ]
    Properties:
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  DashboardDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: SSODashboardInternetGateway
    Properties:
      RouteTableId:
        Ref: SSODashboardRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SSODashboardInternetGateway
  SSODashboardSubnet1:
    Type: "AWS::EC2::Subnet"
    DependsOn: SSODashboardRouteTable
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: True
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard Subnet 1
  SSODashboardSubnet2:
    Type: "AWS::EC2::Subnet"
    DependsOn: SSODashboardRouteTable
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      CidrBlock: "10.0.1.0/24"
      MapPublicIpOnLaunch: True
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard Subnet 2
  SSODashboardSubnet3:
    Type: "AWS::EC2::Subnet"
    DependsOn: SSODashboardRouteTable
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: ""
      CidrBlock: "10.0.2.0/24"
      MapPublicIpOnLaunch: True
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard Subnet 3
  SSODashboardRouteAssoc1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    DependsOn: DashboardDefaultRoute
    Properties:
      RouteTableId:
        Ref: SSODashboardRouteTable
      SubnetId:
        Ref: SSODashboardSubnet1
  SSODashboardRouteAssoc2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    DependsOn: DashboardDefaultRoute
    Properties:
      RouteTableId:
        Ref: SSODashboardRouteTable
      SubnetId:
        Ref: SSODashboardSubnet2
  SSODashboardRouteAssoc3:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    DependsOn: DashboardDefaultRoute
    Properties:
      RouteTableId:
        Ref: SSODashboardRouteTable
      SubnetId:
        Ref: SSODashboardSubnet3
  SSODashboardSecGroup:
    Type: "AWS::EC2::SecurityGroup"
    DependsOn: SSODashboardVPC
    Properties:
      GroupDescription: "Allows ports to web instances of dashboard from ELB."
      VpcId:
        Ref: SSODashboardVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8000'
          ToPort: '8000'
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 10.0.0.0/8
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  SSODashboardELBSecGroup:
    Type: "AWS::EC2::SecurityGroup"
    DependsOn: SSODashboardVPC
    Properties:
      GroupDescription: "Allows access to the ELB listeners."
      VpcId:
        Ref: SSODashboardVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SSO-Dashboard ELB
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    DependsOn: SSODashboardELBSecGroup
    Properties:
      Scheme: internet-facing
      Subnets:
        - Ref: SSODashboardSubnet1
        - Ref: SSODashboardSubnet2
        - Ref: SSODashboardSubnet3
      SecurityGroups:
        - Ref: SSODashboardELBSecGroup
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  ALBHTTPListener:
    Type : AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ApplicationLoadBalancer
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ALBTargetGroup
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  ALBHTTPSListener:
    Type : AWS::ElasticLoadBalancingV2::Listener
    DependsOn: ApplicationLoadBalancer
    Properties:
      Certificates:
        - CertificateArn: !FindInMap [!Ref EnvType, !Ref "AWS::Region", CertificateARN]
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: ALBTargetGroup
      LoadBalancerArn:
        Ref: ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ApplicationLoadBalancer
    Properties:
      HealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 10
      UnhealthyThresholdCount: 2
      HealthCheckPath: /health
      HealthCheckPort: 80
      Name: DashboardWebServers-v1
      Port: 8000
      Protocol: HTTP
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  ALBTargetGroup1:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: ApplicationLoadBalancer
    Properties:
      HealthyThresholdCount: 2
      HealthCheckIntervalSeconds: 10
      UnhealthyThresholdCount: 2
      HealthCheckPath: /health
      HealthCheckPort: 80
      Name: DashboardContentDelivery-v1
      Port: 80
      Protocol: HTTP
      VpcId:
        Ref: SSODashboardVPC
      Tags:
        - Key: Name
          Value: SSO-Dashboard
  SSODashboardLaunchConfigProd:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Condition: UseProdCondition
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [!Ref EnvType, !Ref "AWS::Region", AMI]
      IamInstanceProfile: "sso-dashboard-instance-profile-v1"
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          repo_update: true
          repo_upgrade: all
          runcmd:
            - REGION=$(curl 169.254.169.254/latest/meta-data/placement/availability-zone/ | sed 's/[a-z]$//')
            - sudo start amazon-ssm-agent
            - yum update -y
            - wget https://aws-codedeploy-$REGION.s3.amazonaws.com/latest/install
            - chmod +x ./install
            - ./install auto
            - cd /home/ec2-user
            - sudo pip install awscli --upgrade
            - aws ecr get-login --region us-west-2 --no-include-email | bash
            - docker run -d -e SQS_QUEUE=sso-dashboard-fluentd-sqs -v /var/log:/var/log 371522382791.dkr.ecr.us-west-2.amazonaws.com/sqs-fluentd:latest td-agent -c /etc/td-agent/td-agent.conf
            - rm -rf /home/ec2-user/app
            - mkdir -p /home/ec2-user/app
            - git clone https://github.com/mozilla-iam/sso-dashboard.git /home/ec2-user/app
            - cd /home/ec2-user/app
            - git checkout production
            - chmod +x /home/ec2-user/app/scripts/*
            - /home/ec2-user/app/scripts/build-environment.sh
            - /usr/local/bin/docker-compose up -d
      SecurityGroups:
        - Ref: SSODashboardSecGroup
      InstanceType: "t2.medium"
  SSODashboardLaunchConfigDev:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Condition: UseDevCondition
    DependsOn: [ SSODashboardSubnet1, SSODashboardSubnet2, SSODashboardSubnet3 ]
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [!Ref EnvType, !Ref "AWS::Region", AMI]
      IamInstanceProfile: "sso-dashboard-instance-profile"
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          repo_update: true
          repo_upgrade: all
          runcmd:
            - REGION=$(curl 169.254.169.254/latest/meta-data/placement/availability-zone/ | sed 's/[a-z]$//')
            - sudo start amazon-ssm-agent
            - yum update -y
            - cd /home/ec2-user
            - sudo pip install awscli --upgrade
            - aws ecr get-login --region us-west-2 --no-include-email | bash
            - docker run -d -e SQS_QUEUE=sso-dashboard-fluentd-sqs -v /var/log:/var/log 656532927350.dkr.ecr.us-west-2.amazonaws.com/sqs-fluentd:latest td-agent -c /etc/td-agent/td-agent.conf
            - rm -rf /home/ec2-user/app
            - mkdir -p /home/ec2-user/app
            - git clone https://github.com/mozilla-iam/sso-dashboard.git /home/ec2-user/app
            - cd /home/ec2-user/app
            - chmod +x /home/ec2-user/app/scripts/*
            - /home/ec2-user/app/scripts/build-environment.sh
            - /usr/local/bin/docker-compose up -d
      SecurityGroups:
        - Ref: SSODashboardSecGroup
      InstanceType: "t2.medium"
  HTTPsListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: ALBTargetGroup1
      Conditions:
      - Field: path-pattern
        Values:
        - "/static/*"
      ListenerArn:
        Ref: ALBHTTPSListener
      Priority: 1
  HTTPListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn:
          Ref: ALBTargetGroup1
      Conditions:
      - Field: path-pattern
        Values:
        - "*"
      ListenerArn:
        Ref: ALBHTTPListener
      Priority: 1
  SSODashboardASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    DependsOn: [ SSODashboardSubnet1, SSODashboardSubnet2, SSODashboardSubnet3 ]
    Properties:
      Tags:
        -
          Key: Application
          Value: SSO-Dashboard
          PropagateAtLaunch: true
        -
          Key: Name
          Value: SSO-Dashboard-Worker
          PropagateAtLaunch: true
        -
          Key: Owner
          Value: akrug@mozilla.com
          PropagateAtLaunch: true
      TargetGroupARNs:
         - Ref: ALBTargetGroup
         - Ref: ALBTargetGroup1
      MaxSize: "5"
      MinSize: "2"
      VPCZoneIdentifier:
        - Ref: SSODashboardSubnet1
        - Ref: SSODashboardSubnet2
        - Ref: SSODashboardSubnet3
      LaunchConfigurationName:
        !If [UseProdCondition, Ref: SSODashboardLaunchConfigProd, Ref: SSODashboardLaunchConfigDev]
