version: "2"

services:
  web:
    from: centos:latest
    expose:
      - "8000/tcp"
    ports:
      - "80:80"
      - "8000:8000"
    working_dir: '/sso-dashboard'
    roles:
      - dashboard
    volumes:
      ../:/dashboard
    command: ['/usr/bin/dumb-init', '/usr/bin/start.sh']
registries: {}
